[package]
name = "ols"
version = "0.1.0"
edition = "2021"

[lib]
name = "ols"
crate-type = ["cdylib"]

[dependencies]
nalgebra = "0.34.0"
ndarray = "0.16.1"
pyo3 = { version = "0.21", features = ["extension-module"] }
rand = "0.9.2"
